// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1uDJYfxX-yVym7ex--8zrkZ4NpmOhWOc',
    appId: '1:463054909191:web:fc3fd7151780957cdcdfa2',
    messagingSenderId: '463054909191',
    projectId: 'notify52-e3444',
    authDomain: 'notify52-e3444.firebaseapp.com',
    storageBucket: 'notify52-e3444.appspot.com',
    measurementId: 'G-P5N1R1RD2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVi05RRevQJGcSUCjtqAMD11UhcRmiOo',
    appId: '1:463054909191:android:1fa6f2e4e9e6cd78dcdfa2',
    messagingSenderId: '463054909191',
    projectId: 'notify52-e3444',
    storageBucket: 'notify52-e3444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCpezp_sbMjVsxLNfeFcuVnaQmRHxvSfM',
    appId: '1:463054909191:ios:787cd18319290322dcdfa2',
    messagingSenderId: '463054909191',
    projectId: 'notify52-e3444',
    storageBucket: 'notify52-e3444.appspot.com',
    iosBundleId: 'com.example.notifi52',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCpezp_sbMjVsxLNfeFcuVnaQmRHxvSfM',
    appId: '1:463054909191:ios:dbe4b2e8df6ef35edcdfa2',
    messagingSenderId: '463054909191',
    projectId: 'notify52-e3444',
    storageBucket: 'notify52-e3444.appspot.com',
    iosBundleId: 'com.example.notifi52.RunnerTests',
  );
}
